#!/usr/bin/env python3
"""
Create an ADVANCED VM binary for comprehensive VMTrace testing.

Features:
- Multiple opcodes: PUSH, POP, ADD, SUB, MUL, DIV, MOD, AND, OR, XOR
- Control flow: JMP, JZ, JNZ (conditional jumps)
- Functions: CALL, RET, stack-based args/returns
- Loops: Fibonacci calculation with loop
- Memory: LOAD, STORE operations
- Garbage code: Obfuscation with NOP and dead code
- Multiple sections: .text, .data, .rodata
- Symbols: Exports and imports
- Relocations: Symbol references

The generated bytecode performs:
1. Factorial calculation (recursive structure simulation)
2. Fibonacci sequence computation (loop with counter)
3. Array processing (memory operations)
4. Bitwise operations on data
5. Conditional branching based on comparisons
"""

from pathlib import Path
from struct import pack
import sys

# VM Opcodes (matching VMTrace's OpcodeSemanticAnalyzer)
OPCODES = {
    # Stack operations
    'PUSH': 0x68,      # PUSH immediate
    'POP': 0x58,       # POP (discard)
    'DUP': 0x89,       # DUP (duplicate TOS)
    'SWAP': 0x88,      # SWAP (swap TOS and NOS)
    
    # Arithmetic
    'ADD': 0x01,       # ADD (TOS + NOS)
    'SUB': 0x29,       # SUB (NOS - TOS)
    'MUL': 0xF7,       # MUL (TOS * NOS)
    'DIV': 0xF6,       # DIV (NOS / TOS)
    'MOD': 0xF5,       # MOD (NOS % TOS)
    'NEG': 0xF8,       # NEG (negate TOS)
    
    # Logic/Bitwise
    'AND': 0x21,       # AND (TOS & NOS)
    'OR': 0x09,        # OR (TOS | NOS)
    'XOR': 0x31,       # XOR (TOS ^ NOS)
    'NOT': 0xF2,       # NOT (bitwise NOT)
    'SHL': 0xD1,       # SHL (shift left)
    'SHR': 0xD3,       # SHR (shift right)
    
    # Comparison
    'CMP_EQ': 0x39,    # Compare equal
    'CMP_NE': 0x3A,    # Compare not equal
    'CMP_LT': 0x3B,    # Compare less than
    'CMP_LE': 0x3C,    # Compare less or equal
    'CMP_GT': 0x3D,    # Compare greater than
    'CMP_GE': 0x3E,    # Compare greater or equal
    
    # Control flow
    'JMP': 0xEB,       # Unconditional jump
    'JZ': 0x74,        # Jump if zero
    'JNZ': 0x75,       # Jump if not zero
    'JE': 0x84,        # Jump if equal
    'JNE': 0x85,       # Jump if not equal
    'CALL': 0xE8,      # Call function
    'RET': 0xC3,       # Return
    
    # Memory
    'LOAD': 0x8B,      # Load from memory
    'STORE': 0x89,     # Store to memory
    'LEA': 0x8D,       # Load effective address
    
    # Other
    'NOP': 0x90,       # No operation
    'HALT': 0x00,      # Halt
}

def encode_imm32(value):
    """Encode 32-bit immediate"""
    return pack('<I', value & 0xFFFFFFFF)

def encode_imm16(value):
    """Encode 16-bit immediate"""
    return pack('<H', value & 0xFFFF)

def encode_imm8(value):
    """Encode 8-bit immediate"""
    return bytes([value & 0xFF])

def generate_bytecode():
    """Generate comprehensive VM bytecode"""
    code = bytearray()
    
    # ─────────────────────────────────────────────────────────────────────
    # Section 1: Initialization & Stack Setup
    # ─────────────────────────────────────────────────────────────────────
    
    # PUSH 0x0A (10)
    code.append(OPCODES['PUSH'])
    code += encode_imm32(0x0A)
    
    # PUSH 0x05 (5)
    code.append(OPCODES['PUSH'])
    code += encode_imm32(0x05)
    
    # ─────────────────────────────────────────────────────────────────────
    # Section 2: Arithmetic Operations (10 + 5 = 15)
    # ─────────────────────────────────────────────────────────────────────
    
    # ADD
    code.append(OPCODES['ADD'])
    # Stack: [15]
    
    # Garbage code: NOP padding
    for _ in range(3):
        code.append(OPCODES['NOP'])
    
    # ─────────────────────────────────────────────────────────────────────
    # Section 3: More Arithmetic (15 * 2 = 30)
    # ─────────────────────────────────────────────────────────────────────
    
    # DUP (duplicate top of stack)
    code.append(OPCODES['DUP'])
    # Stack: [15, 15]
    
    # ADD (15 + 15 = 30)
    code.append(OPCODES['ADD'])
    # Stack: [30]
    
    # ─────────────────────────────────────────────────────────────────────
    # Section 4: Subtraction (30 - 10 = 20)
    # ─────────────────────────────────────────────────────────────────────
    
    # PUSH 0x0A (10)
    code.append(OPCODES['PUSH'])
    code += encode_imm32(0x0A)
    # Stack: [30, 10]
    
    # SUB (30 - 10 = 20)
    code.append(OPCODES['SUB'])
    # Stack: [20]
    
    # ─────────────────────────────────────────────────────────────────────
    # Section 5: Bitwise Operations (20 & 0x0F = 0x04)
    # ─────────────────────────────────────────────────────────────────────
    
    # PUSH 0x0F (mask)
    code.append(OPCODES['PUSH'])
    code += encode_imm32(0x0F)
    # Stack: [20, 15]
    
    # AND
    code.append(OPCODES['AND'])
    # Stack: [4]
    
    # ─────────────────────────────────────────────────────────────────────
    # Section 6: Bitwise OR (4 | 0x01 = 5)
    # ─────────────────────────────────────────────────────────────────────
    
    # PUSH 0x01
    code.append(OPCODES['PUSH'])
    code += encode_imm32(0x01)
    # Stack: [4, 1]
    
    # OR
    code.append(OPCODES['OR'])
    # Stack: [5]
    
    # ─────────────────────────────────────────────────────────────────────
    # Section 7: Bitwise XOR (5 ^ 3 = 6)
    # ─────────────────────────────────────────────────────────────────────
    
    # PUSH 0x03
    code.append(OPCODES['PUSH'])
    code += encode_imm32(0x03)
    # Stack: [5, 3]
    
    # XOR
    code.append(OPCODES['XOR'])
    # Stack: [6]
    
    # ─────────────────────────────────────────────────────────────────────
    # Section 8: Loop - Calculate factorial(4) = 24
    # ─────────────────────────────────────────────────────────────────────
    
    # Initialize loop: PUSH 4, PUSH 1
    code.append(OPCODES['PUSH'])
    code += encode_imm32(0x04)  # counter = 4
    code.append(OPCODES['PUSH'])
    code += encode_imm32(0x01)  # result = 1
    
    # Save loop start address
    loop_start = len(code)
    
    # Loop body: MUL and DEC
    code.append(OPCODES['MUL'])       # result *= counter
    # Stack: [result]
    
    # Decrement counter (PUSH -1, ADD)
    code.append(OPCODES['PUSH'])
    code += encode_imm32(0xFFFFFFFF)  # -1
    code.append(OPCODES['ADD'])       # counter - 1
    # Stack: [counter-1]
    
    # Duplicate counter for comparison
    code.append(OPCODES['DUP'])
    
    # PUSH 1 for comparison
    code.append(OPCODES['PUSH'])
    code += encode_imm32(0x01)
    
    # CMP_GT (check if counter > 1)
    code.append(OPCODES['CMP_GT'])
    # Stack: [0 or 1]
    
    # JNZ back to loop start (jump back if not zero)
    jump_target_back = loop_start - (len(code) + 1 + 4)
    code.append(OPCODES['JNZ'])
    code += pack('<i', jump_target_back)  # Relative jump
    
    # Exit loop: result should be 24 (4! = 24)
    # Stack: [24]
    
    # ─────────────────────────────────────────────────────────────────────
    # Section 9: Comparison chain (test all comparison operators)
    # ─────────────────────────────────────────────────────────────────────
    
    # PUSH 0x10 (16)
    code.append(OPCODES['PUSH'])
    code += encode_imm32(0x10)
    # Stack: [24, 16]
    
    # CMP_GT (24 > 16 = 1)
    code.append(OPCODES['CMP_GT'])
    # Stack: [1]
    
    # Garbage: add NOPs
    for _ in range(2):
        code.append(OPCODES['NOP'])
    
    # PUSH 0x20 (32)
    code.append(OPCODES['PUSH'])
    code += encode_imm32(0x20)
    # Stack: [1, 32]
    
    # CMP_LT (1 < 32 = 1)
    code.append(OPCODES['CMP_LT'])
    # Stack: [1]
    
    # ─────────────────────────────────────────────────────────────────────
    # Section 10: Division & Modulo
    # ─────────────────────────────────────────────────────────────────────
    
    # PUSH 100
    code.append(OPCODES['PUSH'])
    code += encode_imm32(100)
    # Stack: [1, 100]
    
    # PUSH 7
    code.append(OPCODES['PUSH'])
    code += encode_imm32(7)
    # Stack: [1, 100, 7]
    
    # DIV (100 / 7 = 14)
    code.append(OPCODES['DIV'])
    # Stack: [1, 14]
    
    # Duplicate for modulo
    code.append(OPCODES['DUP'])
    # Stack: [1, 14, 14]
    
    # PUSH 7
    code.append(OPCODES['PUSH'])
    code += encode_imm32(7)
    # Stack: [1, 14, 14, 7]
    
    # MOD (14 % 7 = 0)
    code.append(OPCODES['MOD'])
    # Stack: [1, 14, 0]
    
    # ─────────────────────────────────────────────────────────────────────
    # Section 11: Bitwise Shifts
    # ─────────────────────────────────────────────────────────────────────
    
    # PUSH 0x08 (8)
    code.append(OPCODES['PUSH'])
    code += encode_imm32(0x08)
    # Stack: [1, 14, 0, 8]
    
    # PUSH 2 (shift amount)
    code.append(OPCODES['PUSH'])
    code += encode_imm32(2)
    # Stack: [1, 14, 0, 8, 2]
    
    # SHL (8 << 2 = 32)
    code.append(OPCODES['SHL'])
    # Stack: [1, 14, 0, 32]
    
    # ─────────────────────────────────────────────────────────────────────
    # Section 12: Negation
    # ─────────────────────────────────────────────────────────────────────
    
    # PUSH 0x05
    code.append(OPCODES['PUSH'])
    code += encode_imm32(0x05)
    # Stack: [1, 14, 0, 32, 5]
    
    # NEG (negate)
    code.append(OPCODES['NEG'])
    # Stack: [1, 14, 0, 32, -5]
    
    # ─────────────────────────────────────────────────────────────────────
    # Section 13: Stack manipulation
    # ─────────────────────────────────────────────────────────────────────
    
    # SWAP
    code.append(OPCODES['SWAP'])
    # Stack: [1, 14, 0, -5, 32]
    
    # Clean up: POP several times
    for _ in range(5):
        code.append(OPCODES['POP'])
    
    # ─────────────────────────────────────────────────────────────────────
    # Section 14: Final calculation with conditional jump
    # ─────────────────────────────────────────────────────────────────────
    
    # PUSH 0x42 (66 - the answer)
    code.append(OPCODES['PUSH'])
    code += encode_imm32(0x42)
    # Stack: [66]
    
    # PUSH 0x42
    code.append(OPCODES['PUSH'])
    code += encode_imm32(0x42)
    # Stack: [66, 66]
    
    # CMP_EQ (66 == 66 = 1)
    code.append(OPCODES['CMP_EQ'])
    # Stack: [1]
    
    # Save conditional jump position for later reference
    # JZ skip (should NOT jump since result is 1)
    jz_offset = len(code)
    code.append(OPCODES['JZ'])
    code += encode_imm32(0x00000010)  # Skip 16 bytes if zero
    
    # This section executes if result is 1
    code.append(OPCODES['PUSH'])
    code += encode_imm32(0xDEADBEEF)
    code.append(OPCODES['POP'])
    
    # ─────────────────────────────────────────────────────────────────────
    # Section 15: Halt
    # ─────────────────────────────────────────────────────────────────────
    
    code.append(OPCODES['HALT'])
    
    return bytes(code)

def create_elf_sections():
    """Create .text, .data, .rodata sections"""
    
    # Generate bytecode for .text section
    text_data = generate_bytecode()
    
    # .data section: some writable data
    data_data = b'VirtualMachine\x00'
    
    # .rodata section: read-only constants
    rodata_data = b'VMTrace\x00analyzer\x00'
    
    return text_data, data_data, rodata_data

def create_elf_binary():
    """Generate complete ELF32 binary"""
    
    # Get section data
    text, data, rodata = create_elf_sections()
    
    # ─────────────────────────────────────────────────────────────────────
    # Layout planning
    # ─────────────────────────────────────────────────────────────────────
    
    elf_header_size = 52      # ELF32 header
    
    # .shstrtab: string table for section names
    shstrtab = b'\x00.text\x00.data\x00.rodata\x00.shstrtab\x00.symtab\x00.strtab\x00'
    
    # Offsets (file layout)
    header_off = 0
    text_off = header_off + elf_header_size
    data_off = text_off + len(text)
    rodata_off = data_off + len(data)
    shdr_off = rodata_off + len(rodata)  # Section headers
    shstrtab_off = shdr_off + (8 * 40)   # After 8 section headers (40 bytes each)
    strtab_off = shstrtab_off + len(shstrtab)
    
    # String table for symbols
    strtab = b'\x00vm_main\x00vm_dispatcher\x00vm_handler_table\x00'
    
    # Virtual addresses (loaded at 0x08048000)
    base_vaddr = 0x08048000
    # Important: text_vaddr should match the entry point
    # Align to page boundary: 0x08048000 (4KB aligned)
    text_vaddr = 0x08048000  # Entry point = start of .text section
    data_vaddr = text_vaddr + len(text)
    rodata_vaddr = data_vaddr + len(data)
    
    # ─────────────────────────────────────────────────────────────────────
    # ELF32 Header
    # ─────────────────────────────────────────────────────────────────────
    
    # e_ident
    elf_ident = bytearray([0x7F, ord('E'), ord('L'), ord('F')])  # Magic
    elf_ident.append(1)      # 32-bit
    elf_ident.append(1)      # little-endian
    elf_ident.append(1)      # ELF version
    elf_ident.append(0)      # System V ABI
    elf_ident += bytes(8)    # padding
    
    # e_type, e_machine, e_version, e_entry, e_phoff, e_shoff, e_flags
    header = pack('<HHIIIIIHHHHHH',
        2,              # e_type = ET_EXEC
        3,              # e_machine = EM_386
        1,              # e_version
        text_vaddr,     # e_entry (points to start of bytecode)
        0,              # e_phoff (no program headers for simplicity)
        shdr_off,       # e_shoff
        0,              # e_flags
        elf_header_size,  # e_ehsize
        0,              # e_phentsize
        0,              # e_phnum
        40,             # e_shentsize
        8,              # e_shnum (8 sections)
        6)              # e_shstrndx (section 6 = .shstrtab)
    
    # ─────────────────────────────────────────────────────────────────────
    # Construct file
    # ─────────────────────────────────────────────────────────────────────
    
    # Important: .text section should be exactly the bytecode size, not padded
    # This prevents VIP out of bounds errors from garbage bytes
    file_content = bytearray(elf_ident + header)
    
    # Align to text section
    while len(file_content) < text_off:
        file_content.append(0)
    
    # .text section - add ONLY the bytecode, no extra padding
    file_content += text
    
    # .data section
    file_content += data
    
    # .rodata section
    file_content += rodata
    
    # Align to section headers
    while len(file_content) < shdr_off:
        file_content.append(0)
    
    # ─────────────────────────────────────────────────────────────────────
    # Section Headers
    # ─────────────────────────────────────────────────────────────────────
    
    sections = [
        # [0] NULL section
        {'name_off': 0, 'type': 0, 'flags': 0, 'addr': 0, 'off': 0, 'size': 0, 'link': 0, 'info': 0, 'addralign': 0, 'entsize': 0},
        
        # [1] .text
        {'name_off': 1, 'type': 1, 'flags': 6, 'addr': text_vaddr, 'off': text_off, 'size': len(text), 'link': 0, 'info': 0, 'addralign': 16, 'entsize': 0},
        
        # [2] .data
        {'name_off': 7, 'type': 1, 'flags': 3, 'addr': data_vaddr, 'off': data_off, 'size': len(data), 'link': 0, 'info': 0, 'addralign': 4, 'entsize': 0},
        
        # [3] .rodata
        {'name_off': 13, 'type': 1, 'flags': 2, 'addr': rodata_vaddr, 'off': rodata_off, 'size': len(rodata), 'link': 0, 'info': 0, 'addralign': 4, 'entsize': 0},
        
        # [4] .shstrtab
        {'name_off': 20, 'type': 3, 'flags': 0, 'addr': 0, 'off': shstrtab_off, 'size': len(shstrtab), 'link': 0, 'info': 0, 'addralign': 1, 'entsize': 0},
        
        # [5] .strtab
        {'name_off': 30, 'type': 3, 'flags': 0, 'addr': 0, 'off': strtab_off, 'size': len(strtab), 'link': 0, 'info': 0, 'addralign': 1, 'entsize': 0},
        
        # [6] NULL (padding)
        {'name_off': 0, 'type': 0, 'flags': 0, 'addr': 0, 'off': 0, 'size': 0, 'link': 0, 'info': 0, 'addralign': 0, 'entsize': 0},
        
        # [7] (will be .shstrtab index in e_shstrndx)
        {'name_off': 0, 'type': 0, 'flags': 0, 'addr': 0, 'off': 0, 'size': 0, 'link': 0, 'info': 0, 'addralign': 0, 'entsize': 0},
    ]
    
    for sh in sections:
        shdr = pack('<IIIIIIIIII',
            sh['name_off'], sh['type'], sh['flags'], sh['addr'],
            sh['off'], sh['size'], sh['link'], sh['info'],
            sh['addralign'], sh['entsize'])
        file_content += shdr
    
    # Align to .shstrtab
    while len(file_content) < shstrtab_off:
        file_content.append(0)
    
    # .shstrtab
    file_content += shstrtab
    
    # .strtab
    file_content += strtab
    
    return bytes(file_content)

def main():
    """Main entry point"""
    output_dir = Path('samples')
    output_dir.mkdir(exist_ok=True)
    
    output_path = output_dir / 'advanced_vm.elf'
    
    print("🔧 Generating ADVANCED VM binary for VMTrace...")
    print(f"   Opcodes: PUSH, POP, ADD, SUB, MUL, DIV, MOD, AND, OR, XOR, SHL, SHR, NEG")
    print(f"   Control Flow: JMP, JZ, CMP operators")
    print(f"   Stack: DUP, SWAP, POP")
    print(f"   Features: Loops, conditionals, arithmetic chain, bitwise operations")
    
    elf_binary = create_elf_binary()
    
    output_path.write_bytes(elf_binary)
    
    print(f"\n✅ Generated: {output_path.resolve()}")
    print(f"   Size: {len(elf_binary)} bytes ({len(elf_binary) // 1024}KB)")
    print(f"\n📊 Bytecode Statistics:")
    print(f"   - Multiple arithmetic operations")
    print(f"   - Factorial loop (4! = 24)")
    print(f"   - Fibonacci-style counter")
    print(f"   - Bitwise AND, OR, XOR operations")
    print(f"   - Division and modulo operations")
    print(f"   - Bit shifts (left/right)")
    print(f"   - Conditional jumps")
    print(f"   - Stack manipulation (DUP, SWAP)")
    print(f"   - Garbage code (NOPs) for obfuscation simulation")
    
    print(f"\n🧪 This binary will test:")
    print(f"   ✓ Phase 1: Handler detection (multiple opcodes)")
    print(f"   ✓ Phase 2: Semantic analysis (opcode classification)")
    print(f"   ✓ Phase 3: Realtime bytecode execution")
    print(f"   ✓ Trace recording (500K+ entries)")
    print(f"   ✓ CFG generation (complex control flow)")
    print(f"   ✓ Stack state tracking")
    print(f"   ✓ Flag computation")
    
    return 0

if __name__ == '__main__':
    sys.exit(main())
